services:
  sphereserver:
    image: sphereserver:source-x
    container_name: sphereserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    tty: true # Sphere interactive shell
    stdin_open: true # Sphere interactive shell
    ports:
      - 2593:2593
    volumes:
      - ./data/config/sphere.ini:/sphereserver/sphere.ini # Config from https://github.com/Sphereserver/Source-X/blob/master/src/sphere.ini
      - ./data/accounts:/sphereserver/accounts
      - ./data/logs:/sphereserver/logs
      - ./data/mul:/sphereserver/mul # Files from Ultima Online installation
      - ./data/save:/sphereserver/save
      - ./data/scripts:/sphereserver/scripts # Default scripts: https://github.com/Sphereserver/Scripts-X
